/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: abdullahyeahyea (https://sketchfab.com/abdullahyeahyea)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-gaming-desk-6f1bc394de704e488d44e77134f23993
Title: Low Poly Gaming Desk
*/
'use client'
import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import exp from 'constants'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
    Object_19: THREE.Mesh
    Object_21: THREE.Mesh
    Object_22: THREE.Mesh
    Object_24: THREE.Mesh
    Object_25: THREE.Mesh
  }
  materials: {
    ['Material.003']: THREE.MeshStandardMaterial
    Plastic: THREE.MeshStandardMaterial
    ['7355608']: THREE.MeshStandardMaterial
    black: THREE.MeshStandardMaterial
    blue_light: THREE.MeshStandardMaterial
    blue: THREE.MeshStandardMaterial
  }
}

// export function Model(props: JSX.IntrinsicElements['group']) {
const HackerRoom = (props: JSX.IntrinsicElements['group']) => {
  const monitorTexture = useTexture('/textures/desk/monitor.png')
  const screenTexture = useTexture('/textures/desk/screen-monitor.png')
  const { nodes, materials } = useGLTF('/models/low_poly_gaming_desk.glb') as GLTFResult
  // useEffect(() => {
  //   if(screenTexture){
  //     screenTexture.flipY = true
  //   }
  // } , [])
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.315}>
        <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
          <group name="table_2" position={[-1.145, -2.841, -1.506]} scale={[1, 1, 0.876]}>
            <mesh
              name="Object_4"
              castShadow
              receiveShadow
              geometry={nodes.Object_4.geometry}
              material={materials['Material.003']}
            />
            <mesh
              name="Object_5"
              castShadow
              receiveShadow
              geometry={nodes.Object_5.geometry}
              material={materials.Plastic}
            />
          </group>
          <group name="monitor_3" position={[-0.913, 0.552, -1.553]} scale={[0.523, 0.1, 0.339]}>
            <mesh
              name="Object_7"
              castShadow
              receiveShadow
              geometry={nodes.Object_7.geometry}
              material={materials['7355608']}
              
            >
              <meshBasicMaterial map={screenTexture} />
            </mesh>
            <mesh
              name="Object_8"
              castShadow
              receiveShadow
              geometry={nodes.Object_8.geometry}
              material={materials.black}

            />
            <mesh
              name="Object_9"
              castShadow
              receiveShadow
              geometry={nodes.Object_9.geometry}
              material={materials.blue_light}
            >
              <meshBasicMaterial map={monitorTexture} />
            </mesh>
          </group>
          <group
            name="keyboard_4"
            position={[-0.899, 0.474, -0.429]}
            rotation={[0, 0, -Math.PI]}
            scale={[-1.405, 0.024, 0.421]}>
            <mesh
              name="Object_11"
              castShadow
              receiveShadow
              geometry={nodes.Object_11.geometry}
              material={materials.blue_light}
            />
            <mesh
              name="Object_12"
              castShadow
              receiveShadow
              geometry={nodes.Object_12.geometry}
              material={materials.black}
            />
          </group>
          <group name="mouse_5" position={[0.793, 0.465, -0.781]} scale={[0.114, 0.107, 0.204]}>
            <mesh
              name="Object_14"
              castShadow
              receiveShadow
              geometry={nodes.Object_14.geometry}
              material={materials.black}
            />
            <mesh
              name="Object_15"
              castShadow
              receiveShadow
              geometry={nodes.Object_15.geometry}
              material={materials.blue_light}
            />
          </group>
          <group name="cpu_6" position={[-2.962, 1.463, -1.59]} scale={[0.438, 1, 1.09]}>
            <mesh
              name="Object_17"
              castShadow
              receiveShadow
              geometry={nodes.Object_17.geometry}
              material={materials.black}
            />
            <mesh
              name="Object_18"
              castShadow
              receiveShadow
              geometry={nodes.Object_18.geometry}
              material={materials.blue_light}
            />
            <mesh
              name="Object_19"
              castShadow
              receiveShadow
              geometry={nodes.Object_19.geometry}
              material={materials.Plastic}
            />
          </group>
          <group
            name="headset_7"
            position={[0.888, 1.043, -1.684]}
            rotation={[-1.702, 0, Math.PI / 2]}
            scale={[-0.235, 0.037, 0.235]}>
            <mesh
              name="Object_21"
              castShadow
              receiveShadow
              geometry={nodes.Object_21.geometry}
              material={materials.black}
            />
            <mesh
              name="Object_22"
              castShadow
              receiveShadow
              geometry={nodes.Object_22.geometry}
              material={materials.blue}
            />
          </group>
          <group name="Plane_9" position={[0.71, 0.474, -0.754]} scale={0.576}>
            <mesh
              name="Object_24"
              castShadow
              receiveShadow
              geometry={nodes.Object_24.geometry}
              material={materials.Plastic}
            />
            <mesh
              name="Object_25"
              castShadow
              receiveShadow
              geometry={nodes.Object_25.geometry}
              material={materials.blue_light}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/low_poly_gaming_desk.glb')

export default HackerRoom   
